import { Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({ subsets: ['latin'] , weight: ['100' , '300' , '400' , '500' , '700' , '900'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` text-charcoal font-medium sm:text-2xl ${roboto.className} max-w-screen max-h-screen`}>{children}</body>
    </html>
  )
}
